CREATE DATABASE MANAGE
USE MANAGE
CREATE TABLE CUSTOMER
(
	ID_CUSTOMER NVARCHAR(100) PRIMARY KEY,
	NAME_CUSTOMER NVARCHAR(900),
	DATE_BIRTH DATETIME,
	CUSTOMER_ADDRESS NVARCHAR(900),
	PHONE_NUMBER INT
)
SET DATEFORMAT DMY
CREATE TABLE EMPLOYEE 
(
	ID_EMPLOYEE NVARCHAR(100) PRIMARY KEY,
	NAME_EMPLOYEE NVARCHAR,
	SPECIALLY NVARCHAR,
	EXP_YEAR INT 
)
CREATE TABLE PRODUCT 
(
	SKU_PRODUCT NVARCHAR(100) PRIMARY KEY,
	QUANTITY_PRODUCT INT,
	NAME_PRODUCT NVARCHAR(100)
)
CREATE TABLE BILL
(
	SKU_PRODUCT NVARCHAR(100),
	ID_CUSTOMER NVARCHAR(100),
	ID_EMPLOYEE NVARCHAR(100),
	NAME_EMPLOYEE NVARCHAR(100),
	DATE_BILL DATETIME,
	FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER,
	FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE,
	FOREIGN KEY (SKU_PRODUCT) REFERENCES PRODUCT
)
SET DATEFORMAT DMY
CREATE TABLE STORECOMPANY 
(
	SKU_PRODUCT NVARCHAR(100),
	NAME_COMPANY NVARCHAR(100),
	PHONE_NUMBER INT,
	QUANTITY_PRODUCT INT,
	FOREIGN KEY (SKU_PRODUCT) REFERENCES PRODUCT 
)
CREATE TABLE RATEPRODUCT 
(
	COMMENT_CUSTOMER NVARCHAR(100),
	ID_CUSTOMER NVARCHAR(100),
	STAR_PRODUCT INT,
	FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER
)
CREATE TABLE STORE
(
	NAME_STORE NVARCHAR(100) PRIMARY KEY,
	PHONE_NUMBER INT
)
CREATE TABLE SELL 
(
	SKU_PRODUCT NVARCHAR(100),
	NAME_STORE NVARCHAR(100),
	FOREIGN KEY (NAME_STORE) REFERENCES STORE
)


SELECT *
FROM 
WHERE 



